services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://url_shortener_api_prod_db:5432/url_shortener_api_prod_db
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET_KEY}
    depends_on:
      - db
    networks:
      - url_shortener_api_prod_network
    healthcheck:
        test: [ "CMD", "pg_isready", "-U", "${DB_USERNAME}", "-d", "url_shortener_api_prod_db" ]
        interval: 5s
        timeout: 30s
        retries: 5

  db:
    image: postgres:15
    container_name: url_shortener_api_prod_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: url_shortener_api_prod_db
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    restart: always
    networks:
      - url_shortener_api_prod_network

volumes:
  data:
    driver: local

networks:
  url_shortener_api_prod_network:
    driver: bridge
